# Generated by chromix from a matugen template. Changes are lost on the
# next theme switch.

set -g chromix_primary {{colors.primary.default.hex_stripped}}
set -g chromix_on_surface {{colors.on_surface.default.hex_stripped}}
set -g chromix_red {{colors.red.default.hex_stripped}}
set -g chromix_yellow {{colors.yellow.default.hex_stripped}}
set -g chromix_magenta {{colors.magenta.default.hex_stripped}}

set -g __fish_git_prompt_color_branch $chromix_primary
set -g fish_color_param $chromix_on_surface
set -g fish_color_autosuggestion $chromix_yellow
set -g fish_color_command $chromix_yellow
